package vista;

import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import javax.swing.JOptionPane;

public class main extends javax.swing.JFrame {

    private final int capitulos_totales = 155;
    private List<Integer> Caps_leidos = new ArrayList<>();
    private int capitulo_actual = -1;
    
    public main() {
        initComponents();
        fondo.requestFocus();
        this.setTitle("RayueloMatic");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        btn_nuevoCap = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Historial = new javax.swing.JTextArea();
        lbl_capitulo = new javax.swing.JLabel();
        btn_Confi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setBackground(new java.awt.Color(59, 129, 172));
        fondo.setMaximumSize(new java.awt.Dimension(606, 466));
        fondo.setMinimumSize(new java.awt.Dimension(606, 466));
        fondo.setPreferredSize(new java.awt.Dimension(606, 466));
        fondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fondoMousePressed(evt);
            }
        });

        btn_nuevoCap.setBackground(new java.awt.Color(255, 255, 255));
        btn_nuevoCap.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_nuevoCap.setForeground(new java.awt.Color(0, 0, 0));
        btn_nuevoCap.setText("Nuevo Capítulo");
        btn_nuevoCap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_nuevoCapMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_nuevoCapMouseExited(evt);
            }
        });
        btn_nuevoCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoCapActionPerformed(evt);
            }
        });

        Historial.setColumns(20);
        Historial.setRows(5);
        jScrollPane1.setViewportView(Historial);

        lbl_capitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_capitulo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_capitulo.setText("Capítulo: ");

        btn_Confi.setBackground(new java.awt.Color(255, 255, 255));
        btn_Confi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Confi.setForeground(new java.awt.Color(0, 0, 0));
        btn_Confi.setText("Leido");
        btn_Confi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ConfiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ConfiMouseExited(evt);
            }
        });
        btn_Confi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ConfiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btn_nuevoCap)
                        .addGap(141, 141, 141)
                        .addComponent(lbl_capitulo))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btn_Confi, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_nuevoCap, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_capitulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Confi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fondoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fondoMousePressed
        fondo.requestFocus();
    }//GEN-LAST:event_fondoMousePressed

    private void btn_nuevoCapMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nuevoCapMouseEntered
        btn_nuevoCap.setBackground(new Color (59,180,255));
    }//GEN-LAST:event_btn_nuevoCapMouseEntered

    private void btn_nuevoCapMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nuevoCapMouseExited
        btn_nuevoCap.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btn_nuevoCapMouseExited

    private void btn_ConfiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ConfiMouseEntered
        btn_Confi.setBackground(new Color (59,180,255));
    }//GEN-LAST:event_btn_ConfiMouseEntered

    private void btn_ConfiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ConfiMouseExited
        btn_Confi.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btn_ConfiMouseExited

    private void btn_nuevoCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoCapActionPerformed
        generarCapitulo();
    }//GEN-LAST:event_btn_nuevoCapActionPerformed

    private void btn_ConfiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ConfiActionPerformed
        confirmarLectura();
    }//GEN-LAST:event_btn_ConfiActionPerformed
    
    private void generarCapitulo() {
        if (Caps_leidos.size() >= capitulos_totales) {
            JOptionPane.showMessageDialog(this, "¡Ya has leído todos los capítulos!");
            return;
        }

        Random random = new Random();
        do {
            capitulo_actual = random.nextInt(capitulos_totales) + 1;
        } while (Caps_leidos.contains(capitulo_actual));

        lbl_capitulo.setText("Capítulo: " + capitulo_actual);
        btn_Confi.setEnabled(true);
    }
    
    private void confirmarLectura() {
        if (capitulo_actual == -1) return;

        Caps_leidos.add(capitulo_actual);
        Historial.append("Capítulo leído: " + capitulo_actual + "\n");
        capitulo_actual = -1;
        lbl_capitulo.setText("Capítulo: ");
        btn_Confi.setEnabled(false);

        if (Caps_leidos.size() >= capitulos_totales) {
            JOptionPane.showMessageDialog(this, "¡Felicidades! Has completado Rayuela");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Historial;
    private javax.swing.JButton btn_Confi;
    private javax.swing.JButton btn_nuevoCap;
    private javax.swing.JPanel fondo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_capitulo;
    // End of variables declaration//GEN-END:variables
}
